plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
}

loom {
	mods {
		"xaero-worldgen" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // sodium+mc1.21.11-0.8.7-fabric
	modImplementation "maven.modrinth:AANobbMI:UddlN6L4"
    // Xaero's World Map+fabric-1.21.11-1.41.2
	modImplementation "maven.modrinth:NcUtCpym:1rgcnGza"
    // Xaero's Minimap+fabric-1.21.11-26.1.4
	modImplementation "maven.modrinth:1bokaNcj:rLF2AwoN"
    // Voxy+0.2.16-beta
	modImplementation "maven.modrinth:fxxUqruK:H3w2nVdU"
    // Voxy worldgen+2.2.4
	modImplementation "maven.modrinth:xT0lnNE9:68QZfMFI"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}
